<a href="https://colab.research.google.com/github/Sandeep4118/colab-project/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pandas

In [ ]:
# Series
# A series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index. and the series will be apply on vertically.

In [ ]:
# Creating Series
# There are mulitple ways to create a pandas series.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)
# you can modify the index using dictonary

1    10
2    20
3    30
dtype: int64

In [ ]:
# Data frames: when you combine multiple series that become data frame.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# creating a data frame
data = {
    'Name':['Tom','Nick','Krish','Jack'],
    'Age':[20,21,19,18],
    'City' :['New York','Paris','Berlin','London'],
    'Salary' :[65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# creating a dataframe using list
data = [
    ['John',20,'New York',65000],
    ['Jane',21,'Paris',70000],
    ['Peter',19,'Berlin',62000],
    ['Mary',18,'London',85000]
]
df2 = pd.DataFrame(data)
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data,columns=col)
df2

    Name  Age      City  Salary
0   John   20  New York   65000
1   Jane   21     Paris   70000
2  Peter   19    Berlin   62000
3   Mary   18    London   85000

In [ ]:
# Selection and Indexing of Columns

In [ ]:
df2['Name']

0     John
1     Jane
2    Peter
3     Mary
Name: Name, dtype: object

In [ ]:
df2['Age']

0    20
1    21
2    19
3    18
Name: Age, dtype: int64

In [ ]:
# Selecting more than 2 columns
df2[['Name','Age','Salary']]

    Name  Age  Salary
0   John   20   65000
1   Jane   21   70000
2  Peter   19   62000
3   Mary   18   85000

In [ ]:
# Creating a new column

In [ ]:
df2['Designation'] = ['Manager','Engineer','Doctor','Teacher']
df2

    Name  Age      City  Salary Designation
0   John   20  New York   65000     Manager
1   Jane   21     Paris   70000    Engineer
2  Peter   19    Berlin   62000      Doctor
3   Mary   18    London   85000     Teacher

In [ ]:
# Removing Columns
# Here axis = 1 means (Vertical)
# and axis = 0 means (Horizontal)
# inplace means removing column permanetly from the dataframe.

In [ ]:
df2.drop(['City','Age'],axis=1)

In [ ]:
df2

    Name  Age      City  Salary
0   John   20  New York   65000
1   Jane   21     Paris   70000
2  Peter   19    Berlin   62000
3   Mary   18    London   85000

In [ ]:
df2

    Name  Salary
0   John   65000
1   Jane   70000
2  Peter   62000
3   Mary   85000

In [ ]:
data = {
    'Name':['Tom','Nick','Krish','Jack'],
    'Age':[20,21,19,18],
    'City' :['New York','Paris','Berlin','London'],
    'Salary' :[65000, 70000, 62000, 85000]
}
df3 = pd.DataFrame(data)

In [ ]:
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# removing elements on row basis
df3.drop(1,axis=0)

    Name  Age      City  Salary
0    Tom   20  New York   65000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# Selecting Rows
# loc means location used for rows

In [ ]:
df3.loc[0]

Name           Tom
Age             20
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
# Selecting Mupltiple Rows
df3.loc[[0,2]]

    Name  Age      City  Salary
0    Tom   20  New York   65000
2  Krish   19    Berlin   62000

In [ ]:
# iloc means index location

In [ ]:
# Selecting Subsets of Rows and Columns
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# Selecting rows and columns at the same time.
# first select rows then columns
df3.loc[[0,1,2]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000
2    Berlin   62000

In [ ]:
# Exercise
df3.loc[[2,3]][['Name','Age']]

    Name  Age
2  Krish   19
3   Jack   18

In [ ]:
# Conditional Selection

In [ ]:
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# I only want to see those people whose age is above 20
df3[df3['Age']>=20]

   Name  Age      City  Salary
0   Tom   20  New York   65000
1  Nick   21     Paris   70000

In [ ]:
# I only want people whose age is greater than or equal to 20 and they belong to paris.
df3[(df3['Age']>=20) & (df3['City']=='Paris')]

   Name  Age   City  Salary
1  Nick   21  Paris   70000

In [ ]:
# Missing Data
# FInding Missing Data
import numpy as np
import pandas as pd

In [ ]:
data = {
    'A':[1, 2, np.nan, 4, 5],
    'B':[1, 2, 3, 4, 5],
    'C' :[1, 2, 3, np.nan,np.nan],
    'D' :[1,np.nan, np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
# NAN - is a null value that's why it's show true.
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
# any missing value in each coloumn.
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
# Remvoing Missing Data works only on rows

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# threshold mean there is given 3 means it must be 3 (not null value) in the rows.
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
# Filing the missing Data

In [ ]:
# Instead of NAN fill the another value
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.fillna(0)
# it doesn't apply to the original df because if you want to change original df you must use inplace=true so that it will change the NAN to 0 permenentatly.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
values = {'A':0,'B':100,'C':300,'D':400}
# coloumn wise
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# if you want to put that value of NAN that is the mean of that table.
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [ ]:
# Merging Joining concatination
import numpy as np
import pandas as pd

In [ ]:
# Merging 2 Dataframes

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [ ]:
# Concatination of 2 dataframes
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2])
# based on columns

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
# based on rows
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
# Joining of 2 Dataframes

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
# join
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [ ]:
# Group By Aggregation

In [1]:
import numpy as np
import pandas as pd

In [2]:
# GroupBy

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [4]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [7]:
# Group by Category and calculate the sum of Sales.
cat = df.groupby('Category')['Sales'].sum()
cat
# Group by Creates an object which we can't see it.

Category
A    570
B    930
Name: Sales, dtype: int64

In [8]:
# Group by store and calculate the sum of Sales.
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [9]:
# Group by multiple columns
# Group by Category and Store
# we do groupby for multiple columns for basically categorical data not a continious data.
# There are two type of data qulatative and quantative, here qulatative means categorial data(like male and female, class A and class B, S1 and S2 etc) and quantative means numerical data like quantity,sales etc.
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [15]:
# Aggregation : finding the value from the multiple things.
# like mean, median,sd, variance etc
df['Sales'].mean()

np.float64(187.5)

In [19]:
# we have aggregation function(agg) also where we can pass all the aggreatation type in one way.
df['Quantity'].agg(['mean','min','max','median','count','std'])

mean      15.375000
min        8.000000
max       25.000000
median    15.000000
count      8.000000
std        5.553313
Name: Quantity, dtype: float64

In [20]:
# Pivot Tables

In [21]:
import numpy as np
import pandas as pd

In [22]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    418     21   John  January      Q1
1  2023-01-02       B   West    574     30   Mary  January      Q1
2  2023-01-03       C  North    214     90    Bob  January      Q1
3  2023-01-04       D  South    716     88  Alice  January      Q1
4  2023-01-05       A   East    181     80   John  January      Q1
5  2023-01-06       B   West    970     62   Mary  January      Q1
6  2023-01-07       C  North    965     28    Bob  January      Q1
7  2023-01-08       D  South    748     91  Alice  January      Q1
8  2023-01-09       A   East    168     47   John  January      Q1
9  2023-01-10       B   West    669     33   Mary  January      Q1
10 2023-01-11       C  North    589     95    Bob  January      Q1
11 2023-01-12       D  South    950     93  Alice  January      Q1
12 2023-01-13       A   East    604     31   John  January      Q1
13 2023-01-14       B   West    458     43   Mary  January      Q1
14 2023-01-15       C  North    376     77    Bob  January      Q1
15 2023-01-16       D  South    414     79  Alice  January      Q1
16 2023-01-17       A   East    324     66   John  January      Q1
17 2023-01-18       B   West    380     93   Mary  January      Q1
18 2023-01-19       C  North    542     56    Bob  January      Q1
19 2023-01-20       D  South    501     93  Alice  January      Q1

In [27]:
pd.pivot_table(df,values = 'Units',index = 'Region',columns = 'Product',aggfunc = 'median')
# some values shows NaN because in a give table if you see that East with B there is no value, so that it gives the NaN.

Product     A     B     C     D
Region
East     47.0   NaN   NaN   NaN
North     NaN   NaN  77.0   NaN
South     NaN   NaN   NaN  91.0
West      NaN  43.0   NaN   NaN

In [28]:
pd.pivot_table(df,values=['Sales','Units'],index = 'Region',columns = 'Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     339.0    NaN    NaN    NaN  49.0   NaN   NaN   NaN
North      NaN    NaN  537.2    NaN   NaN   NaN  69.2   NaN
South      NaN    NaN    NaN  665.8   NaN   NaN   NaN  88.8
West       NaN  610.2    NaN    NaN   NaN  52.2   NaN   NaN

In [29]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [32]:
# Operations
import numpy as np
import pandas as pd

In [33]:
# DataFrames Basic Operations
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [34]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [35]:
# shape give that total number of rows and columns
df1.shape

(5, 3)

In [36]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [38]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [39]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [40]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [41]:
# DataFrames Applying Functions

In [42]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [43]:
# if we want to do only square of the Bth column only so we can create our own functions.

In [44]:
def square(x):
  return x**2

In [45]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [46]:
# if you want to see the changes in the original table then we can put our these data into df1['B']
df1['B'] = df1['B'].apply(square)

In [47]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [50]:
df1['D'] = df1['B'].apply(square)
# here we can automatically the new column D using that function.

In [51]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000