<a href="https://colab.research.google.com/github/Sandeep4118/colab-project/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pandas

In [ ]:
# Series
# A series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index. and the series will be apply on vertically.

In [ ]:
# Creating Series
# There are mulitple ways to create a pandas series.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)
# you can modify the index using dictonary

1    10
2    20
3    30
dtype: int64

In [ ]:
# Data frames: when you combine multiple series that become data frame.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# creating a data frame
data = {
    'Name':['Tom','Nick','Krish','Jack'],
    'Age':[20,21,19,18],
    'City' :['New York','Paris','Berlin','London'],
    'Salary' :[65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# creating a dataframe using list
data = [
    ['John',20,'New York',65000],
    ['Jane',21,'Paris',70000],
    ['Peter',19,'Berlin',62000],
    ['Mary',18,'London',85000]
]
df2 = pd.DataFrame(data)
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data,columns=col)
df2

    Name  Age      City  Salary
0   John   20  New York   65000
1   Jane   21     Paris   70000
2  Peter   19    Berlin   62000
3   Mary   18    London   85000

In [ ]:
# Selection and Indexing of Columns

In [ ]:
df2['Name']

0     John
1     Jane
2    Peter
3     Mary
Name: Name, dtype: object

In [ ]:
df2['Age']

0    20
1    21
2    19
3    18
Name: Age, dtype: int64

In [ ]:
# Selecting more than 2 columns
df2[['Name','Age','Salary']]

    Name  Age  Salary
0   John   20   65000
1   Jane   21   70000
2  Peter   19   62000
3   Mary   18   85000

In [ ]:
# Creating a new column

In [ ]:
df2['Designation'] = ['Manager','Engineer','Doctor','Teacher']
df2

    Name  Age      City  Salary Designation
0   John   20  New York   65000     Manager
1   Jane   21     Paris   70000    Engineer
2  Peter   19    Berlin   62000      Doctor
3   Mary   18    London   85000     Teacher

In [ ]:
# Removing Columns
# Here axis = 1 means (Vertical)
# and axis = 0 means (Horizontal)
# inplace means removing column permanetly from the dataframe.

In [ ]:
df2.drop(['City','Age'],axis=1)

In [ ]:
df2

    Name  Age      City  Salary
0   John   20  New York   65000
1   Jane   21     Paris   70000
2  Peter   19    Berlin   62000
3   Mary   18    London   85000

In [ ]:
df2

    Name  Salary
0   John   65000
1   Jane   70000
2  Peter   62000
3   Mary   85000

In [ ]:
data = {
    'Name':['Tom','Nick','Krish','Jack'],
    'Age':[20,21,19,18],
    'City' :['New York','Paris','Berlin','London'],
    'Salary' :[65000, 70000, 62000, 85000]
}
df3 = pd.DataFrame(data)

In [ ]:
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# removing elements on row basis
df3.drop(1,axis=0)

    Name  Age      City  Salary
0    Tom   20  New York   65000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# Selecting Rows
# loc means location used for rows

In [ ]:
df3.loc[0]

Name           Tom
Age             20
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
# Selecting Mupltiple Rows
df3.loc[[0,2]]

    Name  Age      City  Salary
0    Tom   20  New York   65000
2  Krish   19    Berlin   62000

In [ ]:
# iloc means index location

In [ ]:
# Selecting Subsets of Rows and Columns
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# Selecting rows and columns at the same time.
# first select rows then columns
df3.loc[[0,1,2]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000
2    Berlin   62000

In [ ]:
# Exercise
df3.loc[[2,3]][['Name','Age']]

    Name  Age
2  Krish   19
3   Jack   18

In [ ]:
# Conditional Selection

In [ ]:
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# I only want to see those people whose age is above 20
df3[df3['Age']>=20]

   Name  Age      City  Salary
0   Tom   20  New York   65000
1  Nick   21     Paris   70000

In [ ]:
# I only want people whose age is greater than or equal to 20 and they belong to paris.
df3[(df3['Age']>=20) & (df3['City']=='Paris')]

   Name  Age   City  Salary
1  Nick   21  Paris   70000

In [ ]:
# Missing Data
# FInding Missing Data
import numpy as np
import pandas as pd

In [ ]:
data = {
    'A':[1, 2, np.nan, 4, 5],
    'B':[1, 2, 3, 4, 5],
    'C' :[1, 2, 3, np.nan,np.nan],
    'D' :[1,np.nan, np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
# NAN - is a null value that's why it's show true.
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
# any missing value in each coloumn.
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
# Remvoing Missing Data works only on rows

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# threshold mean there is given 3 means it must be 3 (not null value) in the rows.
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
# Filing the missing Data

In [ ]:
# Instead of NAN fill the another value
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.fillna(0)
# it doesn't apply to the original df because if you want to change original df you must use inplace=true so that it will change the NAN to 0 permenentatly.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
values = {'A':0,'B':100,'C':300,'D':400}
# coloumn wise
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# if you want to put that value of NAN that is the mean of that table.
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [ ]:
# Merging Joining concatination
import numpy as np
import pandas as pd

In [ ]:
# Merging 2 Dataframes

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [ ]:
# Concatination of 2 dataframes
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2])
# based on columns

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
# based on rows
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
# Joining of 2 Dataframes

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
# join
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [ ]:
# Group By Aggregation

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# GroupBy

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
# Group by Category and calculate the sum of Sales.
cat = df.groupby('Category')['Sales'].sum()
cat
# Group by Creates an object which we can't see it.

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by store and calculate the sum of Sales.
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# Group by multiple columns
# Group by Category and Store
# we do groupby for multiple columns for basically categorical data not a continious data.
# There are two type of data qulatative and quantative, here qulatative means categorial data(like male and female, class A and class B, S1 and S2 etc) and quantative means numerical data like quantity,sales etc.
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [ ]:
# Aggregation : finding the value from the multiple things.
# like mean, median,sd, variance etc
df['Sales'].mean()

np.float64(187.5)

In [ ]:
# we have aggregation function(agg) also where we can pass all the aggreatation type in one way.
df['Quantity'].agg(['mean','min','max','median','count','std'])

mean      15.375000
min        8.000000
max       25.000000
median    15.000000
count      8.000000
std        5.553313
Name: Quantity, dtype: float64

In [ ]:
# Pivot Tables

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    418     21   John  January      Q1
1  2023-01-02       B   West    574     30   Mary  January      Q1
2  2023-01-03       C  North    214     90    Bob  January      Q1
3  2023-01-04       D  South    716     88  Alice  January      Q1
4  2023-01-05       A   East    181     80   John  January      Q1
5  2023-01-06       B   West    970     62   Mary  January      Q1
6  2023-01-07       C  North    965     28    Bob  January      Q1
7  2023-01-08       D  South    748     91  Alice  January      Q1
8  2023-01-09       A   East    168     47   John  January      Q1
9  2023-01-10       B   West    669     33   Mary  January      Q1
10 2023-01-11       C  North    589     95    Bob  January      Q1
11 2023-01-12       D  South    950     93  Alice  January      Q1
12 2023-01-13       A   East    604     31   John  January      Q1
13 2023-01-14       B   West    458     43   Mary  January      Q1
14 2023-01-15       C  North    376     77    Bob  January      Q1
15 2023-01-16       D  South    414     79  Alice  January      Q1
16 2023-01-17       A   East    324     66   John  January      Q1
17 2023-01-18       B   West    380     93   Mary  January      Q1
18 2023-01-19       C  North    542     56    Bob  January      Q1
19 2023-01-20       D  South    501     93  Alice  January      Q1

In [ ]:
pd.pivot_table(df,values = 'Units',index = 'Region',columns = 'Product',aggfunc = 'median')
# some values shows NaN because in a give table if you see that East with B there is no value, so that it gives the NaN.

Product     A     B     C     D
Region
East     47.0   NaN   NaN   NaN
North     NaN   NaN  77.0   NaN
South     NaN   NaN   NaN  91.0
West      NaN  43.0   NaN   NaN

In [ ]:
pd.pivot_table(df,values=['Sales','Units'],index = 'Region',columns = 'Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     339.0    NaN    NaN    NaN  49.0   NaN   NaN   NaN
North      NaN    NaN  537.2    NaN   NaN   NaN  69.2   NaN
South      NaN    NaN    NaN  665.8   NaN   NaN   NaN  88.8
West       NaN  610.2    NaN    NaN   NaN  52.2   NaN   NaN

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [ ]:
# Operations
import numpy as np
import pandas as pd

In [ ]:
# DataFrames Basic Operations
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
# shape give that total number of rows and columns
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
# DataFrames Applying Functions

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
# if we want to do only square of the Bth column only so we can create our own functions.

In [ ]:
def square(x):
  return x**2

In [ ]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [ ]:
# if you want to see the changes in the original table then we can put our these data into df1['B']
df1['B'] = df1['B'].apply(square)

In [ ]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [ ]:
df1['D'] = df1['B'].apply(square)
# here we can automatically the new column D using that function.

In [ ]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [ ]:
# Project 1

In [51]:
# loading the data
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv('/content/anime.csv')
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [53]:
# to get only top 5 rows
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [54]:
# Make a new column for episode count, you will see that brackets (), where the episode is written.
# Feature Extraction
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [55]:
def extract_episode(txt):
  check = False
  data = ""
  for i in txt:
    if i == ')':
      # data +=i
      break
    if i == '(':
      check = True
      continue
    if check==True:
      data += i
  return data

In [56]:
df['episode_count'] = df['Title'].apply(extract_episode)

In [57]:
df

,Rank,Title,Score,episode_count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64 eps
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24 eps
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13 eps
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51 eps
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10 eps
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51 eps
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1 eps
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148 eps
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13 eps
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13 eps
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2 eps
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110 eps
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13 eps
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13 eps
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12 eps
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201 eps
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1 eps
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22 eps
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24 eps
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25 eps
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1 eps
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1 eps
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7 eps
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14 eps
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74 eps
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1 eps
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1 eps
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12 eps
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1 eps
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24 eps
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23 eps
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12 eps
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26 eps
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13 eps
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16 eps
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11 eps
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1 eps
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11 eps
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10 eps
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1 eps
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26 eps
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12 eps
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75 eps
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26 eps
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26 eps
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24 eps
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10 eps
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12 eps
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12 eps
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4 eps

In [58]:
df['episode_count'] = df['episode_count'].str.replace("eps","")

In [59]:
df

,Rank,Title,Score,episode_count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4

In [60]:
# Convert episode_count into integer because it is actually a string.
df['episode_count']=df['episode_count'].astype(int)

In [61]:
df

,Rank,Title,Score,episode_count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4

In [62]:
# Make a new column for time stamp.
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [63]:
def extract_timestamp(txt):
  check = False
  data = ""
  for i in range(len(txt)):
    if txt[i] == ')':
      for j in range(i+1,i+20):
        data += txt[j]
        check = True
    if check == True:
      break
  return data

In [64]:
df['episode_timestamp'] = df['Title'].apply(extract_timestamp)

In [65]:
df

,Rank,Title,Score,episode_count,episode_timestamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [66]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

df['Months'] = df['episode_timestamp'].apply(calculate_total_months)

In [67]:
df

,Rank,Title,Score,episode_count,episode_timestamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,8

In [73]:
# which anime has the highest score
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,episode_count,episode_timestamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

In [69]:
# give me top 5 highest scoring anime
# here we use value_counts() it gives the value in desiding order.
# head() gives the value of top five rows
df['Score'].value_counts().head()

Title
Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview       1
Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members                                                           1
Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members                                               1
Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members                                                                1
Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview    1
Name: count, dtype: int64

In [70]:
# which anime has the highest episode count
df[df['episode_count'] == df['episode_count'].max()]

,Rank,Title,Score,episode_count,episode_timestamp,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [71]:
# animes with top 5 episode count
df['Title'].value_counts().head()

Title
Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview       1
Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members                                                           1
Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members                                               1
Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members                                                                1
Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview    1
Name: count, dtype: int64

In [74]:
# which is the longest running anime
df[df['Months'] == df['Months'].max()]

,Rank,Title,Score,episode_count,episode_timestamp,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111

In [75]:
# Project 2

In [137]:
import numpy as np
import pandas as pd

In [138]:
df = pd.read_csv('/content/Countries.csv')

In [139]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [140]:
# data preprosessing : Data preprocessing is the process of cleaning, transforming, and preparing raw data so it can be used for machine learning or data analysis.
# Raw Data → Clean Data → Model Ready Data
# By using Data Cleaning, Handling Missing Values, Encoding (Text → Numbers), Feature Scaling, Removing Outliers.

In [141]:
df.shape

(194, 64)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [143]:
# if there null value exits we can fill out

In [144]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [145]:
# which country has the highest population.
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: object

In [146]:
# what is the captial of the country with highest population.
df[df['population'] == df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [147]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [148]:
# which country has the least population.
df[df['population'] == df['population'].min()][['country','population']]

    country  population
179  Tuvalu       11312

In [149]:
# what is the capital of the country with least population.
df[df['population'] == df['population'].min()][['country','population','capital_city']]

    country  population capital_city
179  Tuvalu       11312     Funafuti

In [150]:
# give me top 5 countries with highest democratic score.
df.sort_values(by = 'democracy_score',ascending = False,inplace=True)
df['country'].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [151]:
# how many total regions are there.
df['region'].value_counts().count()

np.int64(22)

In [152]:
# how many countries lie in Eastern Europe region.
df['region'].value_counts()['Eastern Europe']

np.int64(10)

In [153]:
# who is the political leader of the 2nd highest populated country.
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

In [154]:
# how many countries are there whoes political leaders are unkown.
df[df['political_leader'].isna()]['country'].count()

np.int64(7)

In [155]:
# how many country have Republic in their full name.
count = 0
def counting(txt):
  global count
  if 'republic' in txt.lower():
    count+=1
  return txt
df['country_long'].apply(counting)
print(count)

125

In [158]:
# which country in african region has highest population.
african_df = df[df['continent'] == 'Africa']

In [164]:
african_df[african_df['population'] == african_df['population'].max()]['country' ]

125    Nigeria
Name: country, dtype: object