<a href="https://colab.research.google.com/github/Sandeep4118/colab-project/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pandas

In [ ]:
# Series
# A series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index. and the series will be apply on vertically.

In [ ]:
# Creating Series
# There are mulitple ways to create a pandas series.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)
# you can modify the index using dictonary

1    10
2    20
3    30
dtype: int64

In [ ]:
# Data frames: when you combine multiple series that become data frame.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# creating a data frame
data = {
    'Name':['Tom','Nick','Krish','Jack'],
    'Age':[20,21,19,18],
    'City' :['New York','Paris','Berlin','London'],
    'Salary' :[65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# creating a dataframe using list
data = [
    ['John',20,'New York',65000],
    ['Jane',21,'Paris',70000],
    ['Peter',19,'Berlin',62000],
    ['Mary',18,'London',85000]
]
df2 = pd.DataFrame(data)
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data,columns=col)
df2

    Name  Age      City  Salary
0   John   20  New York   65000
1   Jane   21     Paris   70000
2  Peter   19    Berlin   62000
3   Mary   18    London   85000

In [ ]:
# Selection and Indexing of Columns

In [ ]:
df2['Name']

0     John
1     Jane
2    Peter
3     Mary
Name: Name, dtype: object

In [ ]:
df2['Age']

0    20
1    21
2    19
3    18
Name: Age, dtype: int64

In [ ]:
# Selecting more than 2 columns
df2[['Name','Age','Salary']]

    Name  Age  Salary
0   John   20   65000
1   Jane   21   70000
2  Peter   19   62000
3   Mary   18   85000

In [ ]:
# Creating a new column

In [ ]:
df2['Designation'] = ['Manager','Engineer','Doctor','Teacher']
df2

    Name  Age      City  Salary Designation
0   John   20  New York   65000     Manager
1   Jane   21     Paris   70000    Engineer
2  Peter   19    Berlin   62000      Doctor
3   Mary   18    London   85000     Teacher

In [ ]:
# Removing Columns
# Here axis = 1 means (Vertical)
# and axis = 0 means (Horizontal)
# inplace means removing column permanetly from the dataframe.

In [ ]:
df2.drop(['City','Age'],axis=1)

In [ ]:
df2

    Name  Age      City  Salary
0   John   20  New York   65000
1   Jane   21     Paris   70000
2  Peter   19    Berlin   62000
3   Mary   18    London   85000

In [ ]:
df2

    Name  Salary
0   John   65000
1   Jane   70000
2  Peter   62000
3   Mary   85000

In [ ]:
data = {
    'Name':['Tom','Nick','Krish','Jack'],
    'Age':[20,21,19,18],
    'City' :['New York','Paris','Berlin','London'],
    'Salary' :[65000, 70000, 62000, 85000]
}
df3 = pd.DataFrame(data)

In [ ]:
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# removing elements on row basis
df3.drop(1,axis=0)

    Name  Age      City  Salary
0    Tom   20  New York   65000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# Selecting Rows
# loc means location used for rows

In [ ]:
df3.loc[0]

Name           Tom
Age             20
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
# Selecting Mupltiple Rows
df3.loc[[0,2]]

    Name  Age      City  Salary
0    Tom   20  New York   65000
2  Krish   19    Berlin   62000

In [ ]:
# iloc means index location

In [ ]:
# Selecting Subsets of Rows and Columns
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# Selecting rows and columns at the same time.
# first select rows then columns
df3.loc[[0,1,2]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000
2    Berlin   62000

In [ ]:
# Exercise
df3.loc[[2,3]][['Name','Age']]

    Name  Age
2  Krish   19
3   Jack   18

In [ ]:
# Conditional Selection

In [ ]:
df3

    Name  Age      City  Salary
0    Tom   20  New York   65000
1   Nick   21     Paris   70000
2  Krish   19    Berlin   62000
3   Jack   18    London   85000

In [ ]:
# I only want to see those people whose age is above 20
df3[df3['Age']>=20]

   Name  Age      City  Salary
0   Tom   20  New York   65000
1  Nick   21     Paris   70000

In [ ]:
# I only want people whose age is greater than or equal to 20 and they belong to paris.
df3[(df3['Age']>=20) & (df3['City']=='Paris')]

   Name  Age   City  Salary
1  Nick   21  Paris   70000

In [1]:
# Missing Data
# FInding Missing Data
import numpy as np
import pandas as pd

In [14]:
data = {
    'A':[1, 2, np.nan, 4, 5],
    'B':[1, 2, 3, 4, 5],
    'C' :[1, 2, 3, np.nan,np.nan],
    'D' :[1,np.nan, np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [15]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [16]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [17]:
# NAN - is a null value that's why it's show true.
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [18]:
# any missing value in each coloumn.
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [19]:
# Remvoing Missing Data works only on rows

In [20]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [21]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [26]:
# threshold mean there is given 3 means it must be 3 (not null value) in the rows.
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [27]:
# Filing the missing Data

In [28]:
# Instead of NAN fill the another value
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.fillna(0)
# it doesn't apply to the original df because if you want to change original df you must use inplace=true so that it will change the NAN to 0 permenentatly.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [30]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [32]:
values = {'A':0,'B':100,'C':300,'D':400}
# coloumn wise
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [33]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [34]:
# if you want to put that value of NAN that is the mean of that table.
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0